version: '3.3'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server-nginx/ssl:/usr/src/app/server-nginx/ssl:ro
    build:
      args:
        NGINX_FILE: prod
    environment:
       ENV: prod
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  mongodb:
    ports:
      - 27017
  gateway:
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run prod"
  cache:
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run prod"
  event:
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run prod"
  notify:
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run prod"
  user:
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run prod"
  comment:
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run prod"
    volumes:
      - /usr/src/app/server-comment/node_modules
  client:
    privileged: true
    environment:
      - NODE_ENV=production
    command: npm run build-prod
  