version: '3.3'

services:
  nginx:
    ports:
      - "4000:80"
    build:
      args:
        RUNNING_ENV: dev        
  mongodb:
    ports:
      - "27017:27017"
  cache:
    environment:
      - NODE_ENV=development
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-cache && npm start"
  gateway:
    environment:
      - NODE_ENV=development
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-gateway && npm start"
  user:
    environment:
      - NODE_ENV=development
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-user && npm start"
  comment:
    environment:
      - NODE_ENV=development
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-comment && npm start"
  event:
    environment:
      - NODE_ENV=development
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-event && npm start"
  notify:
    environment:
      - NODE_ENV=development
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../server-notify && npm start"
  client:
    environment:
      - NODE_ENV=development
    command: sh -c "cd ../shared/modules/coinpush && npm run build && cd ../../../client && npm start"
  client-app:
    environment:
      - NODE_ENV=development
    ports:
      - "2222:22"
      - "5554:5554"
    command:
      - /bin/sh
      - -c
      - |
          # npm i
          # cordova platform add android
          npm run emulate-android
  