version: '3.7'

services:
  
  elk:
    build: ./server-elk
    image: sebp/elk
    container_name: elk
    ports:
    - 5601:5601
    - 9200:9200
    - 5044:5044
    environment:
      ELASTICSEARCH_START: 1
      LOGSTASH_START: 1
      KIBANA_START: 1
      ES_CONNECT_RETRY: 180
      LS_OPTS: "--config.reload.automatic"
    volumes:
      - ./server-elk/elasticsearch/_data:/var/lib/elasticsearch
      - ./server-elk/logstash/_data:/usr/local/etc
      - ./server-elk/logstash/conf.d:/etc/logstash/conf.d
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    command: mongod --auth

  redis:
    image: "redis"
    ports:
      - 6379
    container_name: redis
    volumes: 
      - ./_data/redis:/data

  gateway:
    image: registry.coinpush.app/gateway
    container_name: gateway
    build: 
      context: .
      dockerfile: server-gateway/Dockerfile
    ports:
      - 3100:3100
    volumes:
      - ./_config:/usr/src/app/_config
      - ./server-gateway/.tmp:/usr/src/app/server-gateway/.tmp
      - ./server-gateway/_log:/usr/src/app/server-gateway/_log
      - /usr/src/app/server-gateway/node_modules
    links:
      - redis

  cache:
    image: registry.coinpush.app/cache
    container_name: "cache"
    build:
      context: .
      dockerfile: server-cache/Dockerfile
    ports:
      - 3001
    volumes:
      - ./_config:/usr/src/app/_config
      - ./server-cache/_log:/usr/src/app/server-cache/_log
      - /usr/src/app/server-cache/node_modules
    links:
      - redis
      - mongodb

  user:
    image: registry.coinpush.app/user
    container_name: user
    build:
      context: .
      dockerfile: server-user/Dockerfile
    ports:
      - 3008
    volumes:
      - ./_config:/usr/src/app/_config
      - ./server-user/_log:/usr/src/app/server-user/_log
      - /usr/src/app/server-user/node_modules
    links:
      - redis
      - mongodb

  notify:
    image: registry.coinpush.app/notify
    container_name: notify
    build:
      context: .
      dockerfile: server-notify/Dockerfile
    ports:
      - 3010
    volumes:
      - ./_config:/usr/src/app/_config
      - ./server-notify/_log:/usr/src/app/server-notify/_log
      - /usr/src/app/server-notify/node_modules
    links:
      - redis
      - mongodb

  comment:
    image: registry.coinpush.app/comment
    container_name: comment
    build:
      context: .
      dockerfile: server-comment/Dockerfile
    ports:
      - 3009
    volumes:
      - ./_config:/usr/src/app/_config
      - ./server-comment/_log:/usr/src/app/server-comment/_log
      - /usr/src/app/server-comment/node_modules
    links:
      - redis
      - mongodb

  event:
    image: registry.coinpush.app/event
    container_name: event
    build:
      context: .
      dockerfile: server-event/Dockerfile
    ports:
      - 3011
    volumes:
      - ./_config:/usr/src/app/_config
      - ./server-event/_log:/usr/src/app/server-event/_log
      - /usr/src/app/server-event/node_modules
    links:
      - redis
      - mongodb