version: '3.3'

services:
  mongodb:
    ports:
      - 27017:27017
    volumes:
      - ./_data/db:/data/db
  gateway:
    environment:
      - NODE_ENV=production
    command: npm run prod
  cache:
    environment:
      - NODE_ENV=production
    command: npm run prod
  event:
    environment:
      - NODE_ENV=production
    command: npm run prod
  notify:
    environment:
      - NODE_ENV=production
    command: npm run prod
  user:
    environment:
      - NODE_ENV=production
    command: npm run prod
  comment:
    environment:
      - NODE_ENV=production
    command: npm run prod
  cp-client:
    environment:
      - NODE_ENV=production
    command: npm run build-prod
  