version: '3.3'

services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./images:/usr/src/app/images
      - ./client:/usr/src/app/client
      - ./server-nginx/pages:/usr/src/app/server-nginx/pages
      - /etc/letsencrypt:/usr/src/app/server-nginx/ssl
      # - ./server-nginx/ssl:/usr/src/app/server-nginx/ssl
    build:
      args:
        NGINX_FILE: prod
    environment:
       ENV: prod
    command: sh -c "envsubst \"`env | awk -F = '{printf \" $$%s\", $$1}'`\" < /etc/nginx/nginx.conf > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"
  mongodb:
    ports:
      - 27017
  client:
    environment:
      - NODE_ENV=production
    command:
      - /bin/sh
      - -c
      - |
          npm i --only=production
          npm run build
    volumes:
      - /usr/src/app/client/node_modules
  gateway:
    environment:
      - NODE_ENV=production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i --only=production
          npm run build
          npm run prod
    volumes:
      - ./images:/usr/src/app/images
      - /usr/src/app/server-gateway/node_modules
  cache:
    environment:
      - NODE_ENV=production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i --only=production
          npm run build
          npm run prod
    volumes:
      - /usr/src/app/server-cache/node_modules
  event:
    environment:
      - NODE_ENV=production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i --only=production
          npm run build
          npm run prod
    volumes:
      - /usr/src/app/server-event/node_modules
  notify:
    environment:
      - NODE_ENV=production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i --only=production
          npm run build
          npm run prod
    volumes:
      - /usr/src/app/server-notify/node_modules
  user:
    environment:
      - NODE_ENV=production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i --only=production
          npm run build
          npm run prod
    volumes:
      - /usr/src/app/server-user/node_modules
  comment:
    environment:
      - NODE_ENV=production
    command:
      - /bin/sh
      - -c
      - |
          npm run install-shared
          npm i --only=production
          npm run build
          npm run prod
    volumes:
      - /usr/src/app/server-comment/node_modules
  